# Resource 07 - refer the connectivity table above
# Expose your tcp service outside the mesh. Any incoming traffic on port no 7000 will be routed to this service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sms12-virtualservice
spec:
  hosts:
  - "*"
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: sms12.ns1.svc.cluster.local
        port:
          number: 3001
